import React, { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import { studentTeacherContextObj } from '../../contexts/StudentTeacherContext';
import './StudentLearningPath.css'; // We will create this next

function StudentLearningPath() {
  const { users } = useContext(studentTeacherContextObj);
  const [path, setPath] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // 1. Get User ID (Robust check)
    let userId = users?._id;
    if (!userId) {
      const stored = localStorage.getItem("user");
      if (stored) userId = JSON.parse(stored)._id;
    }

    if (!userId) {
      setLoading(false);
      return;
    }

    // 2. Fetch the latest AI Path
    axios.get(`http://localhost:3000/student-api/learning-path/${userId}`)
      .then(res => {
        setPath(res.data.payload);
        setLoading(false);
      })
      .catch(err => {
        console.error("Error fetching learning path:", err);
        setLoading(false);
      });
  }, [users]);

  // Helper function to get color based on difficulty
  const getLevelColor = (level) => {
    switch (level) {
      case 'beginner': return 'success';     // Green
      case 'intermediate': return 'primary'; // Blue/Purple
      case 'advanced': return 'danger';      // Red/Orange
      default: return 'secondary';
    }
  };

  if (loading) return <div className="lp-loading">🤖 AI is thinking...</div>;

  if (!path) {
    return (
      <div className="lp-empty">
        <div className="lp-empty-icon">📊</div>
        <h3>No Learning Path Yet</h3>
        <p>Submit an assignment first! The AI needs your test scores to generate a personalized study plan for you.</p>
      </div>
    );
  }

  return (
    <div className="lp-container">
      {/* HEADER SECTION */}
      <div className="lp-header">
        <div>
          <h2 className="lp-title">Your AI Study Plan</h2>
          <p className="lp-subtitle">Based on your recent performance, here is what we recommend.</p>
        </div>
        <div className={`lp-badge ${getLevelColor(path.difficultyLevel)}`}>
          {path.difficultyLevel} Level
        </div>
      </div>

      {/* HERO CARD: THE PREDICTION */}
      <div className="lp-hero-card">
        <div className="lp-hero-content">
          <h3>Current Focus</h3>
          <p>
            The AI has analyzed your answers and identified that you would benefit most from 
            <strong> {path.difficultyLevel} </strong> level resources right now.
          </p>
        </div>
        <div className="lp-hero-illustration">
          🎯
        </div>
      </div>

      {/* RESOURCES GRID */}
      <h3 className="lp-section-title">📚 Recommended Resources</h3>
      <div className="lp-grid">
        {path.recommendedTopics && path.recommendedTopics.length > 0 ? (
          path.recommendedTopics.map((topic, index) => (
            <div key={index} className="lp-card">
              <div className="lp-card-icon">📖</div>
              <div className="lp-card-info">
                <h4>{topic}</h4>
                <span className="lp-tag">Recommended</span>
              </div>
              <button className="lp-action-btn p-2 rounded-3">Start Learning →</button>
            </div>
          ))
        ) : (
          <p>No specific resources found for this level yet.</p>
        )}
      </div>
      
      <div className="lp-footer">
        Generated by AI Model ({path.generatedBy}) on {new Date(path.createdAt).toLocaleDateString()}
      </div>
    </div>
  );
}

export default StudentLearningPath;